### ISSUE TITLE
Tracker for `aot_eager` to reach 100% passrate on OSS models

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#1091]
TorchDynamo Dashboard shows that Aot eager is not 100% for all the models. This is a tracker for the missing work.

### float32
- [x] hf_BigBird - https://github.com/pytorch/torchdynamo/issues/1291
- [ ] speech_transfomer - https://github.com/pytorch/torchdynamo/issues/1287
- [ ] vision_maskrcnn - Error signature same as #1287. Somehow minifier is not able to repro this.
- [x] BigBird - https://github.com/pytorch/torchdynamo/issues/1291
- [x] DebertaForQuestionAnswering - The error might be well within margin. But waiting for https://github.com/pytorch/torchdynamo/issues/1273
- [x] convit_base
- [x] jx_next_base - https://github.com/pytorch/torchdynamo/issues/1286

### float16 
No new errors

### AMP
- [x] timm_nfnet - Accuracy issue
- [x] timm_efficientdet - Accuracy issue
- [x] mobilevit_s - Accuracy issue
- [x] eca_botnext26ts_256 - Accuracy issue

**Comment by IvanYashchuk** [comment]
Here are a couple of failing models that fail with "RuntimeError: expected scalar type Float but found Half":

- [ ] `python benchmarks/torchbench.py --training -d cuda --fast --accuracy-aot-nop --skip-accuracy-check  --generate-aot-autograd-stats -k mobilenet_v2_quantized_qat --float16`

- [ ] `python benchmarks/torchbench.py --training -d cuda --fast --accuracy-aot-nop --skip-accuracy-check  --generate-aot-autograd-stats -k resnet50_quantized_qat --float16`

**Comment by anijain2305** [comment]
@IvanYashchuk All these models fail in the native Pytorch itself. Basically, they can't survive the float16/amp conversion. We never get to the stage where we could run TorchDynamo on them. So, we are skipping these tests in TorchDynamo nightly.

Let me know if that sounds good.

**Comment by anijain2305** [comment]
Closing in favor of #511
