### ISSUE TITLE
TorchDynamo Alpha User Readiness - Master Tracker

### ISSUE THREAD

**Issue by yanboliang** [pytorch/torchdynamo#1441]
To track TorchDynamo Alpha User Readiness:
* [ ] TorchBench passing rate > 90% 
* [x] Runbook available for environment setup (should include smoke test to verify set up) @williamwen42 
* [x] Published supported feature vs. unsupported features
* [x] Debug runbook
* [x] Bug filing template in GH
