### ISSUE TITLE
Tooling Issue Tracking

### ISSUE THREAD

**Issue by mlazos** [pytorch/torchdynamo#1551]
### Minifier
- [ ] [Accuracy minifier](https://github.com/pytorch/torchdynamo/issues/1526)
- [ ] Ensure FX graphs dumped by hooks and `TORCHINDUCTOR_TRACE=1` are runnable in the minifier
- [ ] https://github.com/pytorch/torchdynamo/issues/1380
- [ ] https://github.com/pytorch/torchdynamo/issues/1377
- [ ] https://github.com/pytorch/torchdynamo/issues/1241
### General UX
- [ ] Single debug folder
- [ ] Enable debug dump with one flag when there is an issue
Automatically run minifier with correct mode setting (aot autograd or dynamo) on exception
- [ ] https://github.com/pytorch/torchdynamo/issues/1383
- [ ] https://github.com/pytorch/torchdynamo/issues/1376

### Documentation
- [ ] Accuracy minifier example in debug runbook
- [ ] FAQ once people have started to try these tools out and we have early feedback

### Compilation Statistics
- [ ] https://github.com/pytorch/torchdynamo/issues/1244

### PyTorch Profiler Integration ([main issue](https://github.com/pytorch/torchdynamo/issues/1541))
- [ ] Fix links missing between CPU and GPU traces (figure out which metadata is required for this)
- [ ] Add support in TorchDynamo to handle profiler context (currently they are ignored)
Currently disabled because most backends don't support it
- [ ] Identify additional requirements for integrating with the profiler infra

### Logging
- [x] [Log steps of compilation](https://github.com/pytorch/torchdynamo/issues/1243)
- [x] Hooks for logging FX graph to external source
- [ ] https://github.com/pytorch/torchdynamo/issues/1462
- [ ] https://github.com/pytorch/torchdynamo/issues/1167
