### ISSUE TITLE
Tracker for peak memory footprint

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#1598]
- [x] @eellison - #1597
- [x] @anijain2305 @stumpOS - https://github.com/pytorch/torchdynamo/issues/1479
- [x] Dashboard - go back to original batch size when the above two issues are fixed
- [ ] Debug excess memory usage from cudagraphs during graph capture (cc: @eellison)
- [x] Resolve fallbacks using real tensors (cc: @eellison )

**Comment by stumpOS** [comment]
I had not started #1479 because of access issues into the cluster. I will see if I can fix it anyway without a larger memory device today (I have an 8GB device)

**Comment by anijain2305** [comment]
No major open issues as of now. Closing this one.
