### ISSUE TITLE
[Inductor] Task Tracker for CPU Backend Optimization

### ISSUE THREAD

**Issue by jgong5** [pytorch/torchdynamo#1728]
This issue summarizes all the completed, WIP and planned tasks about (or related to) TorchInductor CPU backend optimization. Note that the list is not fixed and would grow per benchmark result and feedbacks from maintainers and the community.

### Completed

- [x] https://github.com/pytorch/torchdynamo/pull/1452
- [x] https://github.com/pytorch/torchdynamo/pull/1468
- [x] https://github.com/pytorch/torchdynamo/pull/1486, https://github.com/pytorch/pytorch/pull/87037

### WIP
- [ ] https://github.com/pytorch/torchdynamo/issues/1723
  - [ ] https://github.com/pytorch/pytorch/pull/87068
  - [ ] Explicit vectorization support for FP32 reduction ops
- [ ] https://github.com/pytorch/torchdynamo/issues/1556
- [ ] Conv/Linear post-op fusion for inference
  - [ ] https://github.com/pytorch/pytorch/pull/87063
  - [ ] https://github.com/pytorch/pytorch/pull/87064
  - [ ] https://github.com/pytorch/pytorch/pull/87065
  - [ ] https://github.com/pytorch/pytorch/pull/87066
- [ ] Conv/Linear weight prepack for inference

### Planned (short-term)

- [ ] Explicit vectorization support for BF16 data type
- [ ] Explicit vectorization support for INT8 data type

### Planned (longer than short-term)
- [ ] Codegen for conv/gemm
- [ ] Autotune
- [ ] clang/llvm integration
