### ISSUE TITLE
PyTorch core test with inductor issue tracker

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1772]
The passing rate is tracked at https://github.com/pytorch/torchdynamo/issues/1730

* **test_modules.py**
  - [ ] test_cpu_gpu_parity_nn_AdaptiveAvgPool2d_cuda_float32: networkx.exception.NetworkXError: node sink not in graph
  - [ ] test_memory_format_ao_nn_quantized_MaxPool2d_cuda_float32: assert not memory_format, "TODO"
  - [ ] test_non_contiguous_tensors_nn_AdaptiveAvgPool2d_cuda_float32: RuntimeError: you can only change requires_grad flags of leaf variables
* **test_nn.py**
  - [ ] test_conv_cudnn_nhwc_support_cuda_float32: AssertionError: Tensor.is_contiguous() unhandled kwargs
  - [ ] test_conv_double_backward_cuda_float64 : AssertionError: torch.* op returned non-Tensor _GeneratorContextManager call_function <function flags at 0x7f2db68d1550>
  - [ ] test_conv_double_backward_strided_with_3D_input_and_weight_cuda: AssertionError: ABCMeta
  - [ ] test_AdaptiveLogSoftmax_cuda_fp32: RuntimeError: mm(): functions with out=... arguments don't support automatic differentiation, but one of the arguments requires grad.
  - [ ] test_Bilinear_empty_cuda: IndexError: pop from empty list
  - [ ] test_GroupNorm_general_cuda: SyntaxError: invalid syntax
  - [ ] test_InstanceNorm1d_general_cuda: RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
  - [ ] test_LSTM_grad_and_gradgrad_cuda_float64: ValueError: gradcheck expects at least one input tensor to require gradient, but none of the them have requires_grad=True.
  - [ ] test_batchnorm_eval_cuda_float32: AttributeError: 'NoneType' object has no attribute 'clone'
  - [ ] test_conv_large_cuda: RuntimeError: CUDA error: an illegal memory access was encountered
* **test_torch.py**
  - [ ] test_advancedindex_mixed_cpu_devices_cuda: 
  - [ ] test_addcdiv_cuda_float16: concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
  - [ ] test_assertRaisesRegex_ignore_msg_non_native_device_cuda: SyntaxError: invalid syntax
  - [ ] test_bernoulli_self_cuda_bool: RuntimeError: "check_uniform_bounds" not implemented for 'Bool'
  - [ ] test_cummax_cummin_cuda: torch._inductor.exc.CppCompileError: C++ compile error
  - [ ] test_cumprod_cuda: assert not any(isinstance(x, TensorBox) for x in kwargs.values())
  - [ ] test_pairwise_distance_empty_cuda: TypeError: reduce() of empty sequence with no initial value
  - [ ] test_pin_memory_from_constructor_cuda:  assert not pin_memory
  - [ ] test_scatter_reduce_scalar_cuda_float16: RuntimeError: aten::scatter_reduce_() Expected a value of type 'Tensor' for argument 'src' but instead found type 'int'.
