### ISSUE TITLE
ProxyTensor TorchBench issue tracker

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#331]
Creating a meta-issue to track issues with [python key tracing](https://github.com/pytorch/torchdynamo/blob/main/torchdynamo/optimizations/python_key.py), many of these will likely affect AOT autograd as well.

# Investigated:
- [ ] hf_BigBird: (https://github.com/pytorch/torchdynamo/issues/80#issuecomment-1082675169)
- [ ] moco: https://github.com/pytorch/pytorch/issues/81526
- [ ] speech_transformer: https://github.com/pytorch/pytorch/issues/81529
- [x] tacotron2: `embedding_dense_backward` decomposition appears to not preserve strides in a problematic manner (issue fixed by https://github.com/pytorch/pytorch/pull/81528 but seems like there's more issues).
- [ ] demucs: ProxyTensor doesn't really seem to work with LSTM modules #203 

## Seems to work now?
- [x] quantized models, see #79 

The following fail to trace due to errors
- [ ] maml: requires training mode, would be fixed by #271
- [ ] fastNLP_Bert: Bizarre, generates some very weird graphs.
- [ ] hf_Reformer: fails with `RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn`

Runs but doing possibly wrong things:

The following fails correctness tests:
- [ ] vision_maskrcnn: `Accuracy failed for key name masks INCORRECT`

Reproduce with:
`./torchbench.py -dcuda --python-key --no-skip -k<name>`

cc @Chillee

**Comment by jansel** [comment]
@Chillee is this a new error, or the same as the ones above?
```
cuda eval  pyhpc_isoneutral_mixing            ERROR:root:unhandled error
Traceback (most recent call last):
  File "/home/jansel/torchdynamo/benchmarks/common.py", line 687, in run_one_model
    new_result = model_iter_fn(model, example_inputs)
  File "./benchmarks/torchbench.py", line 314, in forward_pass
    def forward_pass(self, mod, inputs, collect_outputs=True):
  File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 93, in _fn
    return fn(*args, **kwargs)
  File "/home/jansel/functorch/functorch/_src/aot_autograd.py", line 646, in forward
    return compiled_f(
  File "/home/jansel/torchdynamo/torchdynamo/eval_frame.py", line 93, in _fn
    return fn(*args, **kwargs)
  File "/home/jansel/functorch/functorch/_src/aot_autograd.py", line 199, in forward
    fw_module, bw_module = partition_fn(fx_g, joint_inputs)
  File "/home/jansel/functorch/functorch/_src/partitioners.py", line 363, in min_cut_rematerialization_partition
    cut_value, partition = nx.minimum_cut(nx_graph, "source", "sink")
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/networkx/algorithms/flow/maxflow.py", line 458, in minimum_cut
    R = flow_func(flowG, _s, _t, capacity=capacity, value_only=True, **kwargs)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/networkx/algorithms/flow/preflowpush.py", line 421, in preflow_push
    R = preflow_push_impl(G, s, t, capacity, residual, global_relabel_freq, value_only)
  File "/home/jansel/conda/envs/torchdynamo/lib/python3.8/site-packages/networkx/algorithms/flow/preflowpush.py", line 27, in preflow_push_impl
    raise nx.NetworkXError(f"node {str(t)} not in graph")
networkx.exception.NetworkXError: node sink not in graph
```

tts_angular and demucs both fail for the LSTM issue.

I'll submit a fix for Super_SloMo as that was a decomp issue.

**Comment by Chillee** [comment]
This looks like an in-place op error actually (or some other kind of weird graph).

**Comment by jansel** [comment]
Closing this issue as it seems out of date.  I put an up to date list of issues here:
