### ISSUE TITLE
TorchInductor failing training models tracker

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#511]
Currently, 31 models are passing `torchbench.py -d cuda --indcutor --training --float16` mode, this issue tracks the ones that don't work.  For reproducing you should use my `inductor` branch or merge all my pending PRs into your working tree.  Note that due to `dropout()` RNG differences we don't expect accuracy checks to work for many models.

We are still using a lot of fallbacks, and some workarounds that slow things down.  See #327 

## Old failures in inference (that also break training)
- 10 models: #331 
- 5 models: #332

## New failures from training:

Segfault with no error message:
- [ ] attention_is_all_you_need_pytorch

Failing with `RuntimeError: CUDA: Error- invalid value`
- [ ] Background_Matting

Failing with `RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same` or `RuntimeError: expected scalar type Float but found Half`
- [ ] demucs
- [ ] resnet50_quantized_qat
- [ ] mobilenet_v2_quantized_qat

Failing with `NotImplementedError: argument of type: <class 'torch.storage._UntypedStorage'>`.  This one looks like a bug in AOT Autograd. cc @anijain2305 @Chillee 
- [ ] tts_angular
- [ ] mobilenet_v3_large
- [ ] mobilenet_v2

Failing with `torchinductor.exc.LoweringException: AssertionError: View(...`.  This one looks like an inductor bug
- [ ] pytorch_struct

Failing with `KeyError: torch.float16`.  This is an issue of CPU tensors appearing in the graph and then failing to codegen float16 CPU backend code.  Not sure where the CPU tensors are coming from.
- [ ] hf_Bart

Failing with `RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.HalfTensor [4096, 768]] is at version 12; expected version 11 instead.`
- [ ] hf_Albert

cc @ngimel

**Comment by Chillee** [comment]
> Failing with RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same or RuntimeError: expected scalar type Float but found Half

These errors are probably because these models were not set up to support changing the dtype to `fp16`.

**Comment by Chillee** [comment]
If I replace Inductor compilation with no-op (but still use AOTAutograd), I can't repro errors for `hf_Albert`, `hf_Bart`, `mobilenet_v3_large` nor `mobilenet_v2` (for the ones that could feasibly be AOTAutograd issues).

So I suspect they're related to Inductor's lowerings.

**Comment by jansel** [comment]
I updated the list of failures when running in my branch:
- in this issue
- #332
- #519

**Comment by desertfire** [comment]
I found the benchmarks in the `Fixed` section are all showing accuracy errors on my environment (see my comment in https://github.com/pytorch/torchdynamo/issues/530). And they still exist if I skip torch inductor, by returning `module` directly in `fw_compiler` and `bw_compiler` (see [here](https://github.com/pytorch/torchdynamo/blob/dbb005e7429300e6605abdf6533d0d6dac8dabe3/torchinductor/compile_fx.py#L250)).

**Comment by jansel** [comment]
@desertfire you could try `--use-eval-mode` to disable dropout,batchnorm-updated,etc and `--float32`.

If those don't fix it, and returning `module` also doesn't fix it (as you said) then it is either an issue in decomps/refs or an AOT autograd bug.  The next step would be to replace the list of decompositions we pass to AUT autograd with `{}`.  If that fixes it, then try to binary search which decomp is problematic.

**Comment by ezyang** [comment]
I think some of these failures should be prioritized for after Dec 2. https://github.com/pytorch/torchdynamo/issues/1828 this is a c10d api direct usage, in fact the only model in our suite that uses this. We don't have any commitment for raw c10d api usages working.

Are we planning to do a triage?

**Comment by anijain2305** [comment]
> I think some of these failures should be prioritized for after Dec 2. #1828 this is a c10d api direct usage, in fact the only model in our suite that uses this. We don't have any commitment for raw c10d api usages working.
> 
> Are we planning to do a triage?

Yes, we can definitely do a triage and defer some of them.

For now, I would say all the above issues except maybe a couple are relevant for OSS launch.
Most of them are bug fixes hopefully, but couple of them might require some extensive work (or are waiting on upcoming features) like #1872.
