### ISSUE TITLE
Nightly Benchmarking Issue Tracker

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#973]
- [x] Add eager cudagraphs (aot_cudagraphs) - Request from NV Folks and @penguinwu 
Solved by #991 
- [ ] Large batch size and small batch size runs - Request from @Chillee 
- [x] Clean and host the infra in a repo

**Comment by ezyang** [comment]
What is "eager cudagraphs"?

**Comment by ezyang** [comment]
answer: it's aot_cudagraphs

**Comment by anijain2305** [comment]
Added the `aot_cudagraphs` and `eager` in the nightly. THe infra is also hosted at https://github.com/anijain2305/torchdynamo_dashboard

**Comment by anijain2305** [comment]
Closing as obsolete
